import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-[#F0F9FF]`}
      >
        <div className="flex min-h-screen w-full">
          {/* Side Navigation */}
          <nav className="bg-[#FEFEFE] w-[337px] min-h-screen flex-shrink-0">
            {/* Sidebar content will go here */}
          </nav>
          
          {/* Main Content */}
          <main className="flex-1 min-w-0">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
